project:
  type: website
  render:
    - "*.qmd"
    - "final_presenatation.qmd"

website:
  title: "Krish Bothra"
  favicon: Images/favicon-32x32.png
  navbar:
    logo: Images/favicon-32x32.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd


format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: solar
    toc: false
    page-layout: full



